MAGIC_NUMBER = 'DATA'
HEADER_SIZE = 24

RELOFFSET_NULL = (-0x7FFFFFFF) - 1
HEADER_TABLE_OFFSET_OFFSET = 8
TABLE_HEADER_SIZE = 28
SCHEMA_HEADER_SIZE = 24
HEADER_SCHEMA_OFFSET_OFFSET = 16
SCHEMA_COLUMN_OFFSET_OFFSET = 16
TABLE_SCHEMA_OFFSET_OFFSET = 8
SCHEMA_COLUMN_SIZE = 20
